# Generated by Django 4.0.3 on 2022-04-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('path', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.page')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.page')),
            ],
            options={
                'unique_together': {('left', 'right')},
            },
        ),
    ]
